### ISSUE TITLE
Compilation error with unsqueeze function

### ISSUE THREAD

**Issue by wu-haoze** [NeuralNetworkVerification/Marabou#755]
Pulling the latest master resulting and compiling locally with G++ 11.4.0 resulting in the following error:

```
[  1%] Building CXX object CMakeFiles/MarabouHelper.dir/src/input_parsers/OnnxParser.cpp.o
/home/haozewu/Projects/Marabou_dev/Marabou/src/input_parsers/OnnxParser.cpp: In member function ‘void OnnxParser::unsqueeze(onnx::NodeProto&)’:                                                                   
/home/haozewu/Projects/Marabou_dev/Marabou/src/input_parsers/OnnxParser.cpp:1208:66: error: conversion from ‘Vector<long int>’ to non-scalar type ‘Vector<int>’ requested                                         
 1208 |     Vector<SignedTensorIndex> axes = _constantIntTensors[axisName];
      |                                                                  ^
make[2]: *** [CMakeFiles/MarabouHelper.dir/build.make:1518: CMakeFiles/MarabouHelper.dir/src/input_parsers/OnnxParser.cpp.o] Error 1                                                                              
make[1]: *** [CMakeFiles/Makefile2:606: CMakeFiles/MarabouHelper.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

**Comment by wu-haoze** [comment]
Is #756  a reasonable fix?

**Comment by MatthewDaggitt** [comment]
Yes, https://github.com/NeuralNetworkVerification/Marabou/pull/753 and https://github.com/NeuralNetworkVerification/Marabou/pull/748 had a semantic merge conflict. By default Github only picks up on syntactic merge conflicts. To avoid this happening in future, we should turn on Github's merge queue feature!
